mensabot_base_controller:
  ros__parameters:
    
    # Joint names from URDF/XACRO file
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.4                                                # Shortest distance (m) between left and right wheel. 
    wheel_radius: 0.11                                                   # Radius (m) of wheels.

    # Wheel rotation modifiers, can be used to invert rotation due to different mounting directions.
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: -1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom                                                   # Fixed frame for odometry.
    base_frame_id: base_link                                              # Base frame for static robot model.
    publish_rate: 60.                                                     # Publishing rate (Hz) of the odometry and TF messages.
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    position_feedback: true                                               # Use position feedback from hardware.
    open_loop: false                                                      # Calculate odometry from commanded values (true) or from hardware feedback (false).
    enable_odom_tf: true                                                  

    cmd_vel_timeout: 0.5                                                  # Assumed time [s] required to apply a commanded velocity.
    publish_limited_velocity: true                                        # Publish the commanded velocity with limits applied.
    velocity_rolling_window_size: 10                                      # Number of velocity values used to calculate the mean velocity.

    # Linear Limits
    linear.x.max_velocity: 0.2                                            # Max velocity (m/s). 
    linear.x.min_velocity: -0.2                                           # Min velocity (m/s).
    linear.x.max_acceleration: 0.05                                       # Max acceleration (m/s²).
    linear.x.max_deceleration: -0.05                                      # Max deceleration (m/s²).
    linear.x.max_acceleration_reverse: -0.05                              # Max reverse acceleration (m/s²).
    linear.x.max_deceleration_reverse: 0.05                               # Max reverse deceleration (m/s²).
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    # Rotation Limits
    angular.z.max_velocity: 0.2                                           # Max angular velocity (rad/s).
    angular.z.min_velocity: -0.2                                          # Min angular velocity (rad/s).
    angular.z.max_acceleration: 0.1                                       # Max angular acceleration (rad/s²).
    angular.z.max_deceleration: -0.1                                      # Max angular deceleration (rad/s²).
    angular.z.max_acceleration_reverse: -0.1                              # Max angular reverse acceleration (rad/s²).
    angular.z.max_deceleration_reverse: 0.1                               # Max angular reverse decceleration (rad/s²).
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN